parameters:
    binlist.client.base_url:  '%env(BINLIST_BASE_URL)%'
    exchangerates.client.base_url: '%env(EXCHANGERATES_BASE_URL)%'
    exchangerates.client.middleware.auth.api_key: '%env(EXCHANGERATES_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Millon\PhpRefactoring\Service\Contracts\ComissionModifierInterface:
            tags: [ { name: comission.modifier } ]

    Millon\PhpRefactoring\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Millon\PhpRefactoring\Service\ComissionCalculator:
        arguments:
            $comissionModifiers: !tagged comission.modifier
    Millon\PhpRefactoring\Service\Contracts\ComissionCalculatorInterface:
        alias: Millon\PhpRefactoring\Service\ComissionCalculator

    # binlist client configuration
    Millon\PhpRefactoring\Service\Binlist\Client\Client:
        arguments:
            $baseUrl: '%binlist.client.base_url%'
    Millon\PhpRefactoring\Service\Contracts\BinLookUpInterface:
        alias: Millon\PhpRefactoring\Service\Binlist\Client\Client

    # exchangerates client configuration
    exchangerates.client.middleware.auth:
        class: Millon\PhpRefactoring\Service\ExchangeRates\Client\Middleware\Auth
        arguments:
            $apiKey: '%exchangerates.client.middleware.auth.api_key%'
    exchangerates.client.handler_stack:
        class: GuzzleHttp\HandlerStack
        factory: [ 'GuzzleHttp\HandlerStack', 'create' ]
        calls:
            - [ 'push', [ '@exchangerates.client.middleware.auth', 'auth' ] ]
    Millon\PhpRefactoring\Service\ExchangeRates\Client\Client:
        arguments:
            $baseUrl: '%exchangerates.client.base_url%'
            $config:
                handler: '@exchangerates.client.handler_stack'
    Millon\PhpRefactoring\Service\Contracts\ExchangeRatesInterface:
        alias: Millon\PhpRefactoring\Service\ExchangeRates\Client\Client
