parameters:
    binlist.client.base_url:  '%env(BINLIST_BASE_URL)%'
    exchangerates.client.base_url: '%env(EXCHANGERATES_BASE_URL)%'
    exchangerates.client.middleware.auth.api_key: '%env(EXCHANGERATES_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Millon\PhpRefactoring\Service\Comission\Contracts\ComissionModifierInterface:
            tags: [ { name: comission.modifier } ]

    Millon\PhpRefactoring\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # comission calculator
    Millon\PhpRefactoring\Service\Comission\Contracts\ComissionContextInterface:
        alias: Millon\PhpRefactoring\Service\Comission\ComissionContext
    Millon\PhpRefactoring\Service\Comission\ComissionCalculator:
        arguments:
            # $comissionModifiers: !tagged comission.modifier
            # have to pass modifiers by strict order to calculate comission correctly
            $comissionModifiers:
                - '@Millon\PhpRefactoring\Service\Comission\ComissionModifier\Initial'
                - '@Millon\PhpRefactoring\Service\Comission\ComissionModifier\ByCountry'
                - '@Millon\PhpRefactoring\Service\Comission\ComissionModifier\Round'
    Millon\PhpRefactoring\Service\Contracts\ComissionCalculatorInterface:
        alias: Millon\PhpRefactoring\Service\Comission\ComissionCalculator

    # binlist client
    binlist.client:
        class: GuzzleHttp\Client
    Millon\PhpRefactoring\Service\Binlist\Client\Client:
        arguments:
            $baseUrl: '%binlist.client.base_url%'
            $client: '@binlist.client'
    Millon\PhpRefactoring\Service\Contracts\BinLookUpInterface:
        alias: Millon\PhpRefactoring\Service\Binlist\Client\Client

    # exchangerates client
    exchangerates.client.middleware.auth:
        class: Millon\PhpRefactoring\Service\ExchangeRates\Client\Middleware\Auth
        arguments:
            $apiKey: '%exchangerates.client.middleware.auth.api_key%'
    exchangerates.client.handler_stack:
        class: GuzzleHttp\HandlerStack
        factory: [ 'GuzzleHttp\HandlerStack', 'create' ]
        calls:
            - [ 'push', [ '@exchangerates.client.middleware.auth', 'auth' ] ]
    exchangerates.client:
        class: GuzzleHttp\Client
        arguments:
            $config:
                handler: '@exchangerates.client.handler_stack'
    Millon\PhpRefactoring\Service\ExchangeRates\Client\Client:
        arguments:
            $baseUrl: '%exchangerates.client.base_url%'
            $client: '@exchangerates.client'
    Millon\PhpRefactoring\Service\Contracts\ExchangeRatesInterface:
        alias: Millon\PhpRefactoring\Service\ExchangeRates\Client\Client
